pipeline {
    agent any
    
    tools{
        jdk 'java-11'
        maven 'maven'
    }
    
    stages{
        stage('Git-checkout'){
            steps{
                git branch: 'docker' , url: 'https://github.com/DeepikaVKale/DeeDevopsRepo.git'
            }
        }
        stage('Code Compile'){
            steps{
                dir ('webapp')
                    sh 'mvn compile'
            }
        }
        stage('Code Package'){
            steps{
                dir ('webapp')
                    sh 'mvn clean install'
            }
        }
        stage('Build and tag'){
            steps{
                sh 'docker build -t deepikavkale/webapp:1 .'
            }
        }
        stage('Containerisation'){
            steps{
                sh '''
                docker run -it -d --name c1 -p 9008:8080 deepikavkale/webapp:1
                '''
            }
        }
        stage('Login to Docker Hub') {
                    steps {
                        script {
                            withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                                sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                            }
                        }
                    }
        }
         stage('Pushing image to repository'){
            steps{
                sh 'docker push deepikavkale/webapp:1'
            }
        }
    }
}